# Generated by Django 3.2.7 on 2021-10-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Nombre de horario')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='RangoHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_hora', models.CharField(blank=True, max_length=15, null=True, verbose_name='Rango de hora')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de finalizacion')),
            ],
            options={
                'db_table': 'rangohora',
            },
        ),
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Tipo de horario')),
            ],
            options={
                'db_table': 'tipohorario',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10, verbose_name='Dia')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.horario', verbose_name='Horario')),
                ('rango_hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.rangohora', verbose_name='Hora')),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='tipohorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.tipohorario', verbose_name='Tipo de horario'),
        ),
        migrations.CreateModel(
            name='Asueto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asueto', models.CharField(max_length=50, verbose_name='Escriba el nombre del Asueto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='fecha de finalizacion')),
                ('tipohorario', models.ManyToManyField(to='horarios.TipoHorario')),
            ],
            options={
                'db_table': 'asueto',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsigHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalizacion')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de registro')),
                ('usuario_registro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario que asiga horario')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Id del Empleado')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.horario', verbose_name='Id del Horario')),
            ],
            options={
                'verbose_name': 'AsigHorario',
                'verbose_name_plural': 'AsigHorarios',
                'db_table': 'asig_horario',
            },
        ),
    ]
