# Generated by Django 3.2.7 on 2021-10-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_horario', models.CharField(max_length=30, verbose_name='Rango horas')),
                ('fecha_marcacion', models.DateField(verbose_name='Fecha marcacion')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora entrada')),
                ('minutos_entrada_mas', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minutos entrada temporana')),
                ('minutos_entrada_menos', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minutos entrada tardia')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora salida')),
                ('minutos_salida_mas', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minutos salida posterior')),
                ('minutos_salida_menos', models.CharField(blank=True, max_length=10, null=True, verbose_name='Minutos salida temprana')),
                ('entrada_tardia', models.BooleanField(default=False, verbose_name='Entrada tardia')),
                ('salida_temprana', models.BooleanField(default=False, verbose_name='Salida temprana')),
                ('fecha_modificacion', models.DateField(blank=True, null=True, verbose_name='Fecha modificacion')),
                ('usuario_modifico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario modifico')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentario')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.horario', verbose_name='Horario')),
            ],
            options={
                'db_table': 'marcacion',
            },
        ),
        migrations.CreateModel(
            name='Ausencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Rango de hora que se ausentó')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de ausencia')),
                ('esta_faltando', models.BooleanField(default=True)),
                ('justificacion_ausencia', models.CharField(blank=True, max_length=500, null=True, verbose_name='Justificación')),
                ('fecha_modificacion', models.DateField(verbose_name='Fecha que se modificó')),
                ('usuario_modfico', models.CharField(max_length=50, verbose_name='Usuario que modificó')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.horario', verbose_name='Horario')),
            ],
            options={
                'db_table': 'ausencias',
            },
        ),
    ]
