# Generated by Django 3.2.7 on 2021-11-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('horarios', '0001_initial'),
        ('marcacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencias',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ausencias',
            name='fecha_modificacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha que se modificó'),
        ),
        migrations.AlterField(
            model_name='ausencias',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horarios.horario', verbose_name='Horario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ausencias',
            name='usuario_modfico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario que modificó'),
        ),
    ]
