# Generated by Django 3.2.7 on 2022-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacion', '0002_auto_20211103_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlcamaraip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_control', models.CharField(max_length=100, verbose_name='Unidad de Control')),
                ('url_camara_ip', models.CharField(max_length=150, verbose_name='Url de conexión camara ip')),
                ('es_interna', models.BooleanField(default=False, verbose_name='Marcar si es camara interna')),
            ],
            options={
                'db_table': 'urlcamaraip',
            },
        ),
    ]
